services:
  stats-server:
    build: ./stat/stat-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1

  ewm-service:
    build: ./main-service
    image: ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
